In [1]:
import numpy as np

In [2]:
a1 = np.arange(9).reshape(3,3) #3  rows

In [3]:
a2 = np.arange(3).reshape(1,3) #only one row

In [5]:
print(a1 , a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [7]:
a1 + a2 #Add one row of a1 to each row of a2

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])