In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(low=1 , high=100 , size=20).reshape(4,5)

In [3]:
arr1

array([[17, 17, 75, 29, 17],
       [80,  1, 18, 35, 30],
       [50, 91, 54, 57,  9],
       [94, 59, 91,  1, 46]], dtype=int32)

In [14]:
arr1[ :, [0,3]] # Fancy Indexing-----> Getting first and fourth columns

array([[17, 29],
       [80, 35],
       [50, 57],
       [94,  1]], dtype=int32)

In [16]:
arr1[[0,2]]  # Fancy Indexing-----> Getting first and third rows

array([[17, 17, 75, 29, 17],
       [50, 91, 54, 57,  9]], dtype=int32)

In [19]:

#------Indexing with boolean arrays

arr1[arr1>50] #gives array of those num greater than 50

array([75, 80, 91, 54, 57, 94, 59, 91], dtype=int32)

In [20]:
arr1[(arr1>50) & (arr1%2==0)]

array([80, 54, 94], dtype=int32)

In [21]:
arr1[arr1%2!=0] = 69 #make all odd numbers of array to 69

In [22]:
arr1


array([[69, 69, 69, 69, 69],
       [80, 69, 18, 69, 30],
       [50, 69, 54, 69, 69],
       [94, 69, 69, 69, 46]], dtype=int32)