In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
#1-d array
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr2 = np.array([[1,2,3] , [4,5,6]])
#2-d array
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr3 = np.zeros((2,3))
#2X3 order filled with zeros
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr4 = np.ones((3,3))
#3x3 order filled with ones
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr5 = np.identity(5)
#identity matrix of order 5X5
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
arr6 = np.arange(10)
#Array from 0-9
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr7 = np.linspace(2,8,4)
#generates array of 4 numbers starts from 2 to 8 having even space between them 
arr7

array([2., 4., 6., 8.])

In [18]:
arr8 = arr7.copy()
#Copy the Array
arr8

array([2., 4., 6., 8.])