In [1]:
import numpy as np

In [2]:
#Arithmetic Operations
arr1 = np.array([1,2,3,4,5])

In [3]:
arr2 = np.array([5,6,7,8,9])

In [4]:
arr1 + arr2

array([ 6,  8, 10, 12, 14])

In [5]:
arr1-arr2

array([-4, -4, -4, -4, -4])

In [6]:
arr1 * arr2 #vector multipication

array([ 5, 12, 21, 32, 45])

In [7]:
arr1 * 2 #Scaler Multipication

array([ 2,  4,  6,  8, 10])

In [13]:
#Dot Product between different order matrices
arr3 = np.arange(6).reshape(2,3)

In [14]:
arr4 = np.arange(6,12).reshape(3,2)

In [15]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [8]:
arr1 > 2 #Conditional operations

array([False, False,  True,  True,  True])

In [9]:
#Statistics Operations
arr1.mean() #Mean

np.float64(3.0)

In [10]:
arr1.std() #Standard Deviation

np.float64(1.4142135623730951)

In [11]:
np.median(arr1)

np.float64(3.0)

In [16]:
#Math Operations
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [17]:
np.exp(arr1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [18]:
np.sqrt(arr1) #-------> Instance Function

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [20]:
arr1.max()  #------> Static Function

np.int64(5)