In [1]:
import numpy as np

In [2]:
#Reshaping in numpy
arr1 = np.arange(6).reshape(2,3)

In [3]:
arr2 = np.arange(6,12).reshape(3,2)


In [4]:
#Changing 2-d array to 1-d
arr1.ravel()

array([0, 1, 2, 3, 4, 5])

In [5]:
#Transposing the array
arr2.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [7]:
#splitting

arr3 = np.arange(9).reshape(3,3)

In [8]:
arr3


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.hsplit(arr3 , 3) #Horizontal Splitting

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [11]:
np.vsplit(arr3 , 3) #Vertical Splitting

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [13]:
#stacking
arr1 = np.array([[1,2,3] , [4,5,6]])


In [14]:
arr2 = np.array([[6,7,8] , [8,9,10]])

In [15]:
np.hstack((arr1 , arr2))

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  8,  9, 10]])

In [17]:
np.vstack((arr1 , arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])